### ISSUE TITLE
Any stable link to download latest clap-validator binaries?

### ISSUE THREAD

**Issue by sadko4u** [free-audio/clap-validator#7] opened 2023-01-04 11:19 UTC
Hello!

I'm thinking on integrating `clap-validator` as a part of CI to my project - [LSP Plugins](https://github.com/sadko4u/lsp-plugins/).
Here's the [example of current CI pipeline](https://github.com/lsp-plugins/lsp-plugins-mb-compressor/actions/runs/3831341987).
It is OK to build the latest `clap-validator` from source but requires some time.
It would be nice to have a stable link to download the archive with binaries just to unpack them and run inside of the CI.

**Comment by robbert-vdh** [comment] 2023-01-04 15:14
Duplicate of #8.

**Closed by robbert-vdh** 2023-01-04 15:14 UTC
